### ISSUE TITLE
Incorrect Behavior in Docstring Example of grab_all()

### ISSUE THREAD

**Issue by YisusChrist** [Julynx/string_grab#1]
The provided docstring example for the `grab_all` function exhibits incorrect behavior when using certain input values. The issue arises when searching for substrings that start with "Http " and end with " OK". The current example demonstrates that the function should yield "200" and "404", but it only yields "200" as the output. This discrepancy in behavior needs to be addressed and documented correctly in the docstring example.

**[Current Docstring](https://github.com/Julynx/string_grab/blob/main/string_grab/string_grab.py#L44):**
```python
Yield all substrings from a string.

Usage:
    grab_all("Http 200 OK Http 404 Not Found", start="Http ", end=" OK")
    >> ("200", "404")

Args:
    text (str): The string to be searched.
    start (str): The start of the substring.
    end (str): The end of the substring.

Yields:
    str: The next substring between the start and end strings.
```

If you take a look at the text introduced and argument values, you will see that it searches for strings that start with **"Http "** and end with **" OK"** which is clearly not the case of **"404"**.

**Expected Output:**
Therefore, the correct output for the provided example should be:
```python
("200")
```

**Suggested Fix:**
Update the docstring example to demonstrate the correct behavior of the function when using the given input values.

**Comment by Julynx** [comment]
That is indeed a typo, thanks for noticing!
Fixed by 9e053cbd02fdcbf791a6f09d59453d0f50b18bd1
